language: ruby
rvm:
- ruby-head
before_script: gem install jekyll -v 2.0.3
script: jekyll build --destination out
notifications:
  flowdock:
    secure: "Jxa0H+CH4MN5eN2mdU3996A1QKHAXOPYEC36a3XX8jwci0zw4gHTeHQNhPPsGpU2BoUf6eLBa09HPIKee/3pTeqV9hXhnWObPS+jI33IZDY0baNHRqC7hmNZpOHJraPKZQlvA+a+i9vx5P28T639hd+oAtD8Gmjh9DamoBYsFEA="
deploy:
  provider: s3
  access_key_id: AKIAJVTGGFJZUS6TBIMQ
  bucket: blog.stockflare.com
  skip_cleanup: true
  local-dir: out
  edge: true
  region: us-east-1
  endpoint: s3-us-east-1.amazonaws.com
  on:
    branch: master
  secret_access_key:
    secure: "Wqq8S6cIZRH8zv5K+vMx0bGbdO0dsauafCNUv+nWWMXQIbRjS+5y+g4NoXxAV165KSAhvbb+nKhrV7u3QYVlMozOwMMKSnZSxTVmIf0bK7inIoYWR2WtmC/MwPtW0bZcraO6q5vEEKTRy/tDHnUcGx3/XOa9bqGZrJ8fVnPtD3Q="
