# Site settings
title: Stockflare helps you find great stock ideas
email: info@stockflare.com
description: "Stockflare is a great place to search for new stocks. You can also see if Wall Street thinks your portfolio is any good or not."
baseurl: "http://blog.stockflare.com"
url: "http://blog.stockflare.com"

# Build settings
markdown: kramdown
permalink: pretty
