# Site settings
title: Stockflare - Helps you find great stock ideas
email: info@stockflare.com
description: "Stockflare provides Great Ideas"
baseurl: "http://blog.stockflare.com"
url: "http://blog.stockflare.com"

# Build settings
markdown: kramdown
permalink: pretty
