# Site settings
title: Stockflare - Great Ideas.
email: info@stockflare.com
description: "Stockflare provides Great Ideas"
baseurl: "http://stockflare.com"
url: "http://blog.stockflare.com"

# Build settings
markdown: kramdown
permalink: pretty
